### PR TITLE
Fix issue #202 Unexpected event"External IP updated"

### PR DESCRIPTION
**Pull request by ssancese**
Ignore external IP address changes when notifying IFTTT
Minor changes to condition checking

### CODE REVIEW

**Review by zhatt — COMMENTED** [review]
This just disables the IP change reporting. The real fix that is needed is in handling of the proxy in the weather server https://github.com/OpenSprinkler/OpenSprinkler-Weather/blob/286e87c812f461f46f0f9e6fd04ff62aaf178384/routes/weather.ts#L172

**Comment by ssancese** [comment]
@zhatt you might be right, I'm not that deep in the understanding of the whole thing but I just can't understand why IP change should be reported along with weather info.
IP changes should be treated  and reported separately and possibly reporting should be enabled by the user through UI settings.

**Review by rayshobby — APPROVED** [review]

**Comment by rayshobby** [comment]
External IP (eip) change is useful for those who use port forwarding for remote access. The reason it is coupled with weather update is that eip change is sent back to the controller through weather query -- the controller itself cannot detect eip change, only an external server can, so while it seems unrelated to weather change, this is the easiest way to detect eip change. This is similar to time-zone change -- it isn't directly related to weather data but it's convenient to detect time-zone change in the same weather query. I agree that the real fix is to fix the weather server so it won't cause false positives about eip change. For now I will accept your PR. The upcoming firmware 2.2.0 supports OpenThing Cloud (OTC) connection, people won't need to set up port forwarding any more for remote access. Thus it's not longer necessary to get notified about eip change. In the future we will fix the weather server code and probably add a different flag for eip change.

**Comment by Nu11u5** [comment]
I understand that there is a technical case for communicating an external IP change to the controller, but the feature seems to not be working correctly.

I am constantly getting EIP change notifications, and every time the listed IP has nothing to do with my ISP connection.

Usually what is returned is in the 162.158.62/23 network, which is owned by Cloudflare.  Sometimes it even replies with 127.0.0.1.  I suspect there is an issue with the EIP detection service, which I am guessing is hosted behind Cloudflare.

My router's WAN IP is public and not NATed, and I am not connecting through a VPN service.

**Comment by rayshobby** [comment]
I am not sure if you read my message: I acknowledged that the EIP change has false positives, so it's sending notifications when it shouldn't. Therefore I merged this PR which disables EIP change notification for now. Given that firmware 2.2.0 no longer requires port forwarding, most users won't need to know their EIP anymore.

**Pull request merged**
